name: linux

on:
  push:
    paths-ignore:
     - 'README.md'
  pull_request:
    paths-ignore:
     - 'README.md'
  workflow_dispatch:
    inputs:
      version:
        description: dummy
        default: dummy

defaults:
  run:
    shell: bash

jobs:

  test-linux:
    name: Linux test
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v5

      - name: install deps
        run: |
               sudo apt-get update
               sudo apt-get install openjdk-17-jdk-headless openjdk-17-jdk
               sudo apt-get install imagemagick
               sudo apt-get install libv4l-0 libv4l-dev
               sudo apt-get install xdotool xclip
               sudo apt-get install x11-apps x11-utils
               sudo apt-get install lwm fvwm
               sudo apt-get install xvfb

      - name: show installed font packages
        run: |
               dpkg -l|grep font

      - name: install fonts
        run: |
               sudo apt-get install xfonts-utils xfonts-scalable xfonts-encodings xfonts-base xfonts-75dpi xfonts-100dpi
               sudo apt-get install fonts-noto-color-emoji
               sudo apt-get install fonts-dejavu fonts-dejavu-core fonts-freefont-ttf
               sudo apt-get install xfonts-wqy \
               xfonts-efont-unicode xfonts-efont-unicode-ib xfonts-intl-chinese xfonts-intl-chinese-big \
               xfonts-intl-asian xfonts-intl-arabic xfonts-intl-european xfonts-unifont \
                fonts-dejavu-core \
                fonts-dejavu-extra \
                fonts-droid-fallback \
                fonts-guru \
                fonts-guru-extra \
                fonts-horai-umefont \
                fonts-kacst \
                fonts-kacst-one \
                fonts-khmeros-core \
                fonts-lao \
                fonts-liberation \
                fonts-lklug-sinhala \
                fonts-lohit-guru \
                fonts-nanum \
                fonts-noto-cjk \
                fonts-opensymbol \
                fonts-roboto \
                fonts-roboto-hinted \
                fonts-sil-abyssinica \
                fonts-sil-padauk \
                fonts-stix \
                fonts-symbola \
                fonts-takao-pgothic \
                fonts-thai-tlwg \
                fonts-tibetan-machine \
                fonts-tlwg-garuda \
                fonts-tlwg-kinnari \
                fonts-tlwg-laksaman \
                fonts-tlwg-loma \
                fonts-tlwg-mono \
                fonts-tlwg-norasi \
                fonts-tlwg-purisa \
                fonts-tlwg-sawasdee \
                fonts-tlwg-typewriter \
                fonts-tlwg-typist \
                fonts-tlwg-typo \
                fonts-tlwg-umpush \
                fonts-tlwg-waree \
                fonts-unfonts-core

      - name: compile
        run:  |
          javac -Xlint:deprecation jshowarch.java

      - name: create runscript
        run: |
             printf '#!/bin/bash\n' > /tmp/a.sh
             printf 'xclock -digital -geometry 300x45+100+688 &\n' >> /tmp/a.sh
             printf 'cd /home/runner/work/jshowarch/jshowarch/\n' >> /tmp/a.sh
             printf 'java jshowarch 300 200 200 90 46 &\n' >> /tmp/a.sh
             printf 'sleep 5\n' >> /tmp/a.sh
             printf 'pwd\n' >> /tmp/a.sh
             printf 'import -window root /tmp/screenshot-linux_before_wm.png\n' >> /tmp/a.sh
             printf 'sleep 1\n' >> /tmp/a.sh
             printf 'fvwm2 &' >> /tmp/a.sh
             printf 'sleep 10\n' >> /tmp/a.sh
             printf 'import -window root /tmp/screenshot-linux.png\n' >> /tmp/a.sh
             cat /tmp/a.sh
             chmod a+rx /tmp/a.sh

      - name: startup-app
        run: |
             pwd
             ls -al
             xvfb-run --server-args="-screen 0 1024x768x24" --auto-servernum /tmp/a.sh
             cp -av /tmp/screenshot-linux.png screenshot-linux.png

      - name: upload-screenshots
        uses: actions/upload-artifact@v4
        with:
          name: screenshot-linux
          path: /tmp/screenshot-linux.png

      - name: upload-screenshots
        uses: actions/upload-artifact@v4
        with:
          name: screenshot-linux_before_wm
          path: /tmp/screenshot-linux_before_wm.png

      - name: Upload to nightly release
        uses: ncipollo/release-action@v1
        if: github.ref == 'refs/heads/master'
        with:
          allowUpdates: true
          tag: nightly
          omitBodyDuringUpdate: true
          omitNameDuringUpdate: true
          prerelease: true
          replacesArtifacts: true
          token: ${{ secrets.GITHUB_TOKEN }}
          artifacts: "screenshot-linux.png"

