name: macos-arm

on:
  push:
    paths-ignore:
     - 'README.md'
  pull_request:
    paths-ignore:
     - 'README.md'
  workflow_dispatch:
    inputs:
      version:
        description: dummy
        default: dummy

defaults:
  run:
    shell: bash

jobs:

  test-macos:
    name: MacOS-arm test
    runs-on: macos-14
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Install Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: |
            17

      - name: show architecture
        run:  uname -m

      - name: show architecture
        run:  uname -p

      - name: install imagemagick
        run:  brew install imagemagick

      - name: compile
        run:  |
          javac -Xlint:deprecation jshowarch.java

      - name: run
        run:  |
          screencapture -T 5 -x -t png /Users/runner/screenshot-macos-14.png &
          java jshowarch &
          sleep 5

      - name: upload-screenshots
        uses: actions/upload-artifact@v4
        with:
          name: screenshot-macos-arm
          path: |
            /Users/runner/screen*.png

      - name: Upload to nightly release
        uses: ncipollo/release-action@v1
        if: github.ref == 'refs/heads/master'
        with:
          allowUpdates: true
          tag: nightly
          omitBodyDuringUpdate: true
          omitNameDuringUpdate: true
          prerelease: true
          replacesArtifacts: true
          token: ${{ secrets.GITHUB_TOKEN }}
          artifacts: "/Users/runner/screenshot-macos-14.png"

